modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="mythic_botany_tweaker"
version="1.0.0"
displayName="Mythic Botany Tweaker"
logoFile=""
credits=""
authors="Biggest_Xuan" #optional
description='''
'''
[[dependencies.mythic_botany_tweaker]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mythic_botany_tweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mythic_botany_tweaker]]
    modId="crafttweaker"
    mandatory=true
    versionRange="[7.1.2.500,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mythic_botany_tweaker]]
    modId="mythicbotany"
    mandatory=true
    versionRange="[1.16.5-1.4.15,)"
    ordering="NONE"
    side="BOTH"
